apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: anyuid
    creationTimestamp: 2020-09-07T19:58:47Z
    labels:
      name: mariadb
    name: mariadb
    namespace: wp
    resourceVersion: "30478"
    selfLink: /api/v1/namespaces/wp/pods/mariadb
    uid: 8a73d835-f144-11ea-955c-0242ac110012
  spec:
    containers:
    - env:
      - name: MYSQL_ROOT_PASSWORD
        value: redhat
      - name: MYSQL_USER
        value: wordpress
      - name: MYSQL_PASSWORD
        value: redhat
      - name: MYSQL_DATABASE
        value: wordpress
      image: mariadb:10.5.2-bionic
      imagePullPolicy: IfNotPresent
      name: mariadb
      ports:
      - containerPort: 3306
        name: wordpressdb-svc
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
          - SYS_CHROOT
        privileged: false
        seLinuxOptions:
          level: s0:c7,c4
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: wordpressdb-persistent-storage
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-5f96f
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-9jcfn
    nodeName: fbc2d707e218
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      seLinuxOptions:
        level: s0:c7,c4
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: wordpressdb-persistent-storage
      persistentVolumeClaim:
        claimName: claim-mariadb
    - name: default-token-5f96f
      secret:
        defaultMode: 420
        secretName: default-token-5f96f
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2020-09-07T19:58:47Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2020-09-07T19:59:06Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2020-09-07T19:58:47Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://c7f169daea2cf61b94c10f8f55a3c213da1a0f83a258d03f7645b3cdac59de7c
      image: docker.io/mariadb:10.5.2-bionic
      imageID: docker-pullable://docker.io/mariadb@sha256:53ed8f768e21368f4f8cf50c8f7dd031d13c5125f337d54289067f8cdd6235f3
      lastState: {}
      name: mariadb
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2020-09-07T19:59:05Z
    hostIP: 172.17.0.18
    phase: Running
    podIP: 172.20.0.2
    qosClass: BestEffort
    startTime: 2020-09-07T19:58:47Z
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: anyuid
    creationTimestamp: 2020-09-07T19:59:01Z
    labels:
      name: wordpress
    name: wordpress
    namespace: wp
    resourceVersion: "30488"
    selfLink: /api/v1/namespaces/wp/pods/wordpress
    uid: 9322ed10-f144-11ea-955c-0242ac110012
  spec:
    containers:
    - env:
      - name: WORDPRESS_DB_HOST
        value: mariadb
      - name: WORDPRESS_DB_PASSWORD
        value: redhat
      - name: WORDPRESS_DB_USER
        value: wordpress
      - name: WORDPRESS_DB_NAME
        value: wordpress
      image: wordpress
      imagePullPolicy: Always
      name: wordpress
      ports:
      - containerPort: 80
        name: wordpress-svc
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
          - SYS_CHROOT
        privileged: false
        seLinuxOptions:
          level: s0:c7,c4
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/www/html
        name: wordpress-persistent-storage
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-5f96f
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-9jcfn
    nodeName: fbc2d707e218
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      seLinuxOptions:
        level: s0:c7,c4
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: wordpress-persistent-storage
      persistentVolumeClaim:
        claimName: claim-wordpress
    - name: default-token-5f96f
      secret:
        defaultMode: 420
        secretName: default-token-5f96f
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2020-09-07T19:59:01Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2020-09-07T19:59:33Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2020-09-07T19:59:01Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://d1361b1eb09fa72e1c306d7a1fa84250a23976ca93b0895fb7d8938724df5b6d
      image: docker.io/wordpress:latest
      imageID: docker-pullable://docker.io/wordpress@sha256:44606029218d6a6fdd7c98520b14ff1a738b155a4cd7f14b49451ae4eca49e2b
      lastState: {}
      name: wordpress
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2020-09-07T19:59:32Z
    hostIP: 172.17.0.18
    phase: Running
    podIP: 172.20.0.3
    qosClass: BestEffort
    startTime: 2020-09-07T19:59:01Z
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
